# Generated by Django 3.2.5 on 2022-02-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupcustomerdetails',
            old_name='assignedto',
            new_name='telecall',
        ),
    ]
