# Generated by Django 3.2.5 on 2022-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenterapp', '0002_rename_assignedto_followupcustomerdetails_telecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupcustomerdetails',
            name='is_followup',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
